### ISSUE TITLE
Add ability to customize CredentialsProvider used by the WebClient

### ISSUE THREAD

**Issue by medzin** [SeleniumHQ/htmlunit-driver#1]
Currently there is no way to customize CredentialsProvider used by the WebClient. It makes difficult to configure for example a NTLM authentication or Digest authentication.

**Comment by rbri** [comment]
You can use the methods

* org.openqa.selenium.htmlunit.HtmlUnitDriver.createWebClient(BrowserVersion)
* org.openqa.selenium.htmlunit.HtmlUnitDriver.modifyWebClient(WebClient)

to customize the WebClient. Please have a look at the sample code at https://github.com/SeleniumHQ/htmlunit-driver.
