### ISSUE TITLE
selenium-standalone server 2.53.0: HtmlUnitDriver class not found

### ISSUE THREAD

**Issue by Alexhha** [SeleniumHQ/htmlunit-driver#10]
Hello,

Could anyone point me - how can I run selenium in standalone mode with HtmlUnitDriver? I have tried the following but without success

```
# java -cp ".;./libs/" -jar selenium-2.53.0.jar -Dwebdriver.chrome.driver=chromedriver
13:09:29.084 INFO - Launching a standalone Selenium Server
13:09:29.338 INFO - Java: Oracle Corporation 25.77-b03
13:09:29.339 INFO - OS: Linux 2.6.32-573.18.1.el6.x86_64 amd64
13:09:29.422 INFO - v2.53.0, with Core v2.53.0. Built from revision 35ae25b
...
13:09:29.657 INFO - Driver class not found: org.openqa.selenium.htmlunit.HtmlUnitDriver
13:09:29.657 INFO - Driver provider org.openqa.selenium.htmlunit.HtmlUnitDriver is not registered
13:09:30.010 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
13:09:30.010 INFO - Selenium Server is up and running

```

```
# ls
chromedriver htmlunit-driver-standalone-2.20.jar  libs  selenium-2.53.0.jar

# ls ./libs/
htmlunit-driver-standalone-2.20.jar
```

**Comment by lukeis** [comment]
http://stackoverflow.com/a/18413058/725944

java ignores the -cp when you specify -jar, you need to launch it the way the example shows in the [README](https://github.com/SeleniumHQ/htmlunit-driver#deploying-htmlunitdriver-to-selenium-server)

**Comment by Alexhha** [comment]
But I want to run in standalone mode, not in Grid. Or the command would be the same?

**Comment by lukeis** [comment]
then point your "-jar" to the htmlunit-driver-standalone jar file instead?

**Comment by lukeis** [comment]
and yes, using the -cp way would be the same for non-grid

**Comment by Alexhha** [comment]
> then point your "-jar" to the htmlunit-driver-standalone jar file instead?

I get the following error

```
# java -jar htmlunit-driver-standalone-2.20.jar
no main manifest attribute, in htmlunit-driver-standalone-2.20.jar
```

I just want to run selenium server in standalone mode with htmlunit driver support. I'm using codeception framework with the following settings

```
modules:
    enabled:
        - \Helper\Acceptance
        - WebDriver:
                browser: htmlunit
                url: http://127.0.0.1/
                port: 4444

```

> and yes, using the -cp way would be the same for non-grid

and what class should I use instead of **_org.openqa.grid.selenium.GridLauncher_** for standalone mode?

**Comment by lukeis** [comment]
you use GridLauncher for standalone mode, it's what the selenium-server uses, only if you use the command line argument "-role" will it launch in hub or node mode.

**Comment by Alexhha** [comment]
I got it. So these commands would have the same "effect"?

```
# java -jar selenium-2.53.0.jar -Dwebdriver.chrome.driver=chromedriver -host 192.168.127.1 -port 4444
```
```
# java -cp "selenium-2.53.0.jar" org.openqa.grid.selenium.GridLauncher -host 192.168.127.1 -port 4444 -Dwebdriver.chrome.driver=chromedriver
```

**Comment by lukeis** [comment]
essentially yes... but keep in mind the "-D" parameters should be BEFORE any -jar or classname listed. otherwise they are treated as command line arguments, rather than setting a system property. It works both ways currently in 2.X of selenium... but in 3.X it will not work, and you must specify it early in the command line.

**Comment by Alexhha** [comment]
Thanks. Will bear in mind

BTW
could add some notice to the example? Because it doesn't work on windows 
```
> java.exe -cp "htmlunit.jar:selenium.jar" org.openqa.grid.selenium.GridLauncher -host 127.0.0.1 -port
 4444 -Dwebdriver.chrome.driver=chromedriver.exe
Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher
```
You must use semicolon as separator
```
> java.exe -cp "htmlunit.jar;selenium.jar" org.openqa.grid.selenium.GridLauncher -host 127.0.0.1 -port
 4444 -Dwebdriver.chrome.driver=chromedriver.exe
22:12:01.471 INFO - Launching a standalone Selenium Server
Setting system property webdriver.chrome.driver to chromedriver.exe
22:12:01.668 INFO - Java: Oracle Corporation 25.91-b14
22:12:01.668 INFO - OS: Windows 7 6.1 x86
22:12:01.679 INFO - v2.53.0, with Core v2.53.0. Built from revision unknown
22:12:01.749 INFO - Driver class not found: com.opera.core.systems.OperaDriver
22:12:01.749 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
22:12:01.757 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:

registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform VISTA
22:12:02.002 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
22:12:02.002 INFO - Selenium Server is up and running
```

**Comment by lukeis** [comment]
this is something java specific... on windows it's ";" but on linux/mac it's ":"

**Comment by Alexhha** [comment]
Yes, probably. I think it would be useful to add some warning for windows users, imho.

Anyway, thanks for your help.
