### ISSUE TITLE
HtmlUnitDriver 2.51.0 pulled from Maven Central depends on HtmlUnit 2.51.0-SNAPSHOT

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/htmlunit-driver#100]
First off, thank you for your continuing efforts to maintain and enhance this driver! I really appreciate all that you do.
I upgraded my Selenium Foundation library to use HtmlUnitDriver 2.51.0 and discovered that it brought in HtmlUnit 2.51.0-SNAPSHOT as a transitive dependency. I managed this up to the official 2.51.0 release, and I see that your POM refers to this now as well.
This may be impossible, given the way that Maven repositories work, but is there any way to push updated artifacts that replace the SNAPSHOT dependency reference with the official release?

**Comment by rbri** [comment]
Oooh, i have no idea what was going wrong here - outside of being a bit in a hurry during the last release.
Many thanks for the hint. Will try to make a new minor release later today.

**Comment by sbabcoc** [comment]
Don't rush on my account. Were you able to verify what I ran into? I've rushed a few releases myself, but you have the extra challenge of staying in sync with the browser version. (The only library I have with that characteristic is my `guava-agent` project.)

**Comment by ismail261** [comment]
@rbri Any update on minor release?

**Comment by rbri** [comment]
version 2.52.0 is available - include a fix for this.

Thanks for the report.
