### ISSUE TITLE
Add support for data urls?

### ISSUE THREAD

**Issue by skyhirider** [SeleniumHQ/htmlunit-driver#102]
The Firefox driver (and it seems the Chrome driver as well) support data urls, a way to call 
`        driver.get("data:text/html;charset=utf-8," + pageAsText);
`
to load a text string as a page. I know HtmlUnit can do this by calling its custom method, but would it be possible to expand this to work with the common interface other drivers are using?

Calling this now returns a java.net.MalformedURLException

I would like to write a single test that could be ran on multiple drivers by calling driver.get() instead of having to add a custom implementation for HtmlUnit driver.

More info on data urls:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
https://newbedev.com/put-a-string-with-html-javascript-into-selenium-webdriver
https://stackoverflow.com/a/65446466/1341887

**Comment by sbabcoc** [comment]
What is the objective for using this functionality? Are you testing an automation framework of some sort? For my Selenium Foundation framework, I acquire drivers from a local Selenium Grid instance, and I host static test pages with simple servlets on the Grid hub. The advantage is that this works for all the platforms and browsers I want to test on - even mobile browsers. It would be easy to add a feature to upload new content to these servlets, but I've never seen the need.

**Comment by skyhirider** [comment]
My goal is to create small unit tests where I load the page from memory. I am not using grid as I did not need it yet, but would like to test if my page objects work by using mocks of web pages. Mainly using HtmlUnit so everything is in Java and can be easily tested as there is a way to load strings as pages in HtmlUnit.

But I wanted to test another scenario where I would run the same html string against Firefox and Htmlunit to compare the behavior as I ran into a page where the same xpath works on Firefox but not on Htmlunit.

I just think overall having a common way to do this would be nice, and if a method already exists in the java browser then the driver could call this and it should be feasible to add.

**Comment by rbri** [comment]
Will have a look, but I think this is something HtmlUnit has to support like the simulated browsers do

**Comment by skyhirider** [comment]
Thanks rbri, wasn't sure if I should open this issue for HtmlUnit or the driver, figured I post it here. Can open the same issue on the HtmlUnit github as well if you want to track it.

**Comment by rbri** [comment]
HtmlUnit is able to handle this kind of urls - have done the fix here in the driver and added some tests

Btw this adds also support for the javascript: protocol.

Many thanks for this report.

**Comment by skyhirider** [comment]
Thanks for the fix, by javascript protocol you mean using "data:application/javascript" and loading a javascript ?

Searching for javascript protocol resulted in seemingly unrelated results.

Or did you mean now being able to call scrips like this "data:text/html,<script>alert('hi');</script>" ?
