### ISSUE TITLE
Make release with Selenium 4 support

### ISSUE THREAD

**Issue by mabartos** [SeleniumHQ/htmlunit-driver#105]
In the latest master, there's a support for Selenium 4, which has been released recently. It'd be great to release new version of _htmlunit-driver_ in order to ensure compatibility with the Selenium 4.

@rbri Could you please take a look at it? Thank you.

**Comment by rbri** [comment]
2.x will stay at selenium 3.

Just made a new snapshot build of 3.54.0-SNAPSHOT. This is for selenium 4 and based on HtmlUnit 2.54.0.
We are working on the selenium 4 support but i like to fix some more issues before the final release.

Feel free to open issues for all the problems you are facing when using the new version.

**Comment by JohnA2** [comment]
Thanks. Is 3.54.0-SNAPSHOT available from Maven Central or only by building from sources? I don't see it in https://mvnrepository.com/artifact/org.seleniumhq.selenium/htmlunit-driver , but maybe I'm looking in the wrong place?

**Comment by rbri** [comment]
Its available from sonatype snapshot repo,  will update the readme later. You can have a look at the HtmlUnit github repo site, I use the same approach there

Am 4. November 2021 21:53:46 MEZ schrieb John Anderson ***@***.***>:
>Thanks. Is 3.54.0-SNAPSHOT available from Maven Central or only by building from sources? I don't see it in https://mvnrepository.com/artifact/org.seleniumhq.selenium/htmlunit-driver , but maybe I'm looking in the wrong place?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/SeleniumHQ/htmlunit-driver/issues/105#issuecomment-961411938
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by JohnA2** [comment]
https://oss.sonatype.org/content/repositories/snapshots worked, thanks! I've tried 3.54.0-SNAPSHOT and it works great. I hope there will be a Selenium 4-based final release soon.

**Comment by rbri** [comment]
check https://twitter.com/htmlunit for the progress

**Comment by rbri** [comment]
released, thanks

consider sponsoring if you like to get more support in the future
