### ISSUE TITLE
htmlunit driver not compatible anymore with Selenium 4.3.0

### ISSUE THREAD

**Issue by zniff** [SeleniumHQ/htmlunit-driver#119]
Hi everybody
It looks like the htmlunit-driver 3.62.0 is not compatible anymore with the latest Selenium 4.3.0 version (which obviously had some classes removed):

`The type org.openqa.selenium.interactions.HasInputDevices cannot be resolved. It is indirectly referenced from required .class files`

**Comment by bakersemail** [comment]
Interface is deprecated in previous versions

**Comment by sdutry** [comment]
having the same issue

**Comment by rbri** [comment]
Work has started on this but is is more work than expected, looks like i have to re implement bigger parts of the action handling.

Please
* be a bit patient
* if you use the project for your business think about [sponsoring](https://github.com/sponsors/rbri) my work

**Comment by rbri** [comment]
Work has started on this but is is more work than expected, looks like i have to re implement bigger parts of the action handling.

Please
* be a bit patient
* if you use the project for your business think about [sponsoring](https://github.com/sponsors/rbri) my work

**Comment by rbri** [comment]
will report the progress here on twitter (https://twitter.com/htmlunit)

**Comment by rbri** [comment]
After some days of fighting with the web driver spec i made a first version of Action support working in HtmlUnit driver 2.63.0-SNAPSHOT (compatible with selenium 4.3.0).

Please try and report your findings.

**Comment by sdutry** [comment]
Thx for the effort.

- where can we access the snapshot version?
- is this a typo where it's supposed to be version `3.63.0-SNAPSHOT`

**Comment by rbri** [comment]
Yes @sdutry you are right - version is **3.63.0-SNAPSHOT**

And after the last push all the test in the repo should pass. Thanks ;-)

**Comment by rbri** [comment]
You should be able to use the new snapshot from maven/gradle.
You need to add another repo - see https://github.com/HtmlUnit/htmlunit at the bottom.

**Comment by sdutry** [comment]
thx for the info, i'll try with adding that repo.

when trying to `mvn install` locally, i'm still getting some test failures:

```
[ERROR] Failures:
[ERROR]   ClickTest.detail:215->WebDriverTestCase.verifyTitle2:1095->WebTestCase.assertEquals:262 expected:<[object Event][?undefined?]> but was:<[object Event][?undefined?]>
[ERROR]   ClickTest.detail:215->WebDriverTestCase.verifyTitle2:1095->WebTestCase.assertEquals:262 expected:<[object Event][?undefined?]> but was:<[object Event][?undefined?]>
[ERROR]   ClickTest.detail:215->WebDriverTestCase.verifyTitle2:1095->WebTestCase.assertEquals:262 expected:<[object Event][?undefined?]> but was:<[object Event][?undefined?]>
[ERROR]   ClickTest.detail:215->WebDriverTestCase.verifyTitle2:1095->WebTestCase.assertEquals:262 expected:<[object Event][?undefined?]> but was:<[object Event][?undefined?]>
[ERROR]   ClickTest.detail:215->WebDriverTestCase.verifyTitle2:1095->WebTestCase.assertEquals:262 expected:<[object Event][?undefined?]> but was:<[object Event][?undefined?]>
[INFO]
[ERROR] Tests run: 586, Failures: 5, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by rbri** [comment]
Yes correct, this is source encoding issue. Will fix this durin the next days.Still some work requred to make the project more clean.
But you ca ignore this for the moment ...

**Comment by sdutry** [comment]
some of the tests in my project are failing with the new version of `htmlunit-driver`(`3.63.0-SNAPSHOT`) and `selenium-java` (`4.3.0`). I'll need to do some further investigation to see what the cause of the failures is. 

Will post back when i have more info.

**Comment by sdutry** [comment]
My problem was a typo in my own files, so ignore that.

Works fine for my use case with `htmlunit-driver`(`3.63.0-SNAPSHOT`) and `selenium-java` (`4.3.0`)

**Comment by rbri** [comment]
3.63.0 is released.

**Comment by bakersemail** [comment]
Great stuff! Thanks for updating this so quickly

**Comment by rbri** [comment]
> Great stuff! Thanks for updating this so quickly

Not really quickly but...
