### ISSUE TITLE
Cannot access 'org.openqa.selenium.interactions.HasInputDevices' which is a supertype of 'org.openqa.selenium.htmlunit.HtmlUnitDriver'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by Cyberavater** [SeleniumHQ/htmlunit-driver#121]
I see some version compatibility thing, but it's not clear from the readme file.

Can you explain it elaborately?

build.gradle.kts
```
dependencies {

    testImplementation("org.jetbrains.kotlin:kotlin-test:1.7.10")

    implementation("org.seleniumhq.selenium:selenium-java:4.3.0")
    implementation("org.seleniumhq.selenium:htmlunit-driver:3.62.0")
}
```

**Comment by rbri** [comment]
Yes i have to make it more clear (maybe having a look at the release might be of some help https://github.com/SeleniumHQ/htmlunit-driver/releases)

selenium 4.3.0 -> htmlunit-driver3.63.0
selenium 4.2.1 -> htmlunit-driver3.63.0

Will add some info the the readme later.

**Comment by Cyberavater** [comment]
Thanks for the help <3

**Comment by rbri** [comment]
readme is also updated
