### ISSUE TITLE
Angular support for htmlunitdriver ?

### ISSUE THREAD

**Issue by ybanda** [SeleniumHQ/htmlunit-driver#126]
I have an angular application and wanted to use headless execution . I am wondering to check if htmlunit-driver supports applications built on angular, knockout,vue and other js/ts frameworks.

i tried testing the application with htmlunit-driver, but was not able test angular apps.

**Comment by rbri** [comment]
Sorry this will not work at the moment for two reasons
* Rhino - the js engine used by htmlunit does not support all the modern js features used by angular
* shadow dom support is missing at the moment n HtmlUnit
