### ISSUE TITLE
Where can I find the API docs for htmlunit-driver ?

### ISSUE THREAD

**Issue by manoj9788** [SeleniumHQ/htmlunit-driver#13]
as title.^^

**Comment by asashour** [comment]
Using maven, there is http://repo1.maven.org/maven2/org/seleniumhq/selenium/htmlunit-driver/2.21/htmlunit-driver-2.21-javadoc.jar

**Comment by manoj9788** [comment]
thanks @asashour . I need to update link to the API docs section for htmlunit driver so  raised as an issue to know if there is one online like for other bindings.
Just noticed that, here is no gh-pages branch on this repo so I assume we are yet to create docs for this repo. 
while we had one previously at https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/htmlunit/HtmlUnitDriver.html

**Comment by lukeis** [comment]
published here now:

http://seleniumhq.github.io/htmlunit-driver/index.html

instructions added to the releasing wiki page about how to deploy them

**Comment by manoj9788** [comment]
Awesome as always..! Thanks Luke.
