### ISSUE TITLE
HtmlUnitDriver needs to provide WebDriverInfo and DriverService service providers for Selenium 4 Grid

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/htmlunit-driver#134]
In order for Selenium 4 **NodeOptions** to resolve the "htmlunit" browser name to **HtmlUnitDriver**, it needs an implementation of the **WebDriverInfo** to provide the association. Without this service provider implementation, we get failures like the one shown in the attached Grid 4 server log.

> org.openqa.selenium.grid.config.ConfigException: Unable to find matching driver for Capabilities {browserName: htmlunit, browserVersion: chrome, platformName: Windows 10}

[grid-node-5.log](https://github.com/SeleniumHQ/htmlunit-driver/files/12412482/grid-node-5.log)

**Comment by rbri** [comment]
Will have a look, i guess i can implement WebDriverInfo  for the next release

**Comment by sbabcoc** [comment]
We apparently also need an **HtmlUnitDriverService**, which implements the **DriverService** interface.

**Comment by sbabcoc** [comment]
I abandoned my attempt to stand up a Grid 4 node that provides HtmlUnit sessions. I need to examine the `InMemorySession` feature of Selenium 3 to determine the size and complexity of the implementation.

**Comment by sbabcoc** [comment]
I've created the [HtmlUnit Remote](https://github.com/sbabcoc/HtmlUnit-Remote) project to resolve this issue.
