### ISSUE TITLE
Fetching innerHTML

### ISSUE THREAD

**Issue by ptriller1und1** [SeleniumHQ/htmlunit-driver#148]
I am just in the process of upgrading selenium to the newest version and I am trying to switch to htmluit3 in this process
but I have not figured out how to get innerHTML with the new version

```
    HtmlUnitDriver driver  = new HtmlUnitDriver(false);
    driver.get("https://www.google.de");
    System.out.println(driver.findElement(By.tagName("body")).getAttribute("innerHTML"));
```
This works fine with the old htmlunit driver but returns `null` in the htmlunit3 verions

When tested it with htmlunit3-driver:4.20.0 it returns null
When I tested it with htmlunit-driver:4.13.0 it returns the innerHTML as expected

**Comment by rbri** [comment]
@ptriller1und1 interesting point - at the moment getting javascript properties (like innerHTML) are not supported if js is disabled.

Technically we only have to disable the support if the javascript engine is disabled (for more about the differences see https://www.htmlunit.org/javascript-howto.html#Enable.2FDisable_JavaScript_support).
Will think about that - maybe i have to adjust this...

As a workaround you can do something like

    HtmlUnitDriver driver  = new HtmlUnitDriver(true);
    driver.getWebClient().getOptions().setThrowExceptionOnScriptError(false);
    driver.get("https://www.google.de");
    System.out.println(driver.findElement(By.tagName("body")).getAttribute("innerHTML"));

**Comment by rbri** [comment]
@ptriller1und1 is think you are right in all point here - fixed now.

Will do a release later today.
