### ISSUE TITLE
Script used by RemoteWebElement.isDisplayed() returns 'true' for elements that aren't displayed

### ISSUE THREAD

**Issue by sbabcoc** [SeleniumHQ/htmlunit-driver#149]
The native `HtmlUnitWebElement.isDisplayed()` method behaves as expected, but the script used by **RemoteWebElement** to determine whether a specified element is displayed doesn't behave as expected. (The script is used with W3C-compliant drivers because this legacy function wasn't adopted as part of the W3C specification.)

I've extracted the script and formatted it for reference: [isDisplayed.js](https://github.com/user-attachments/files/15961664/isDisplayed.js.txt)

**Comment by rbri** [comment]
OMG, will work the next days on this. Thanks for pointing at this

**Comment by sbabcoc** [comment]
The element that unexpectedly returns `true` from this script is this:
```
<p id="hidden-para" hidden>This paragraph should be hidden.</p>
```

**Comment by rbri** [comment]
> The element that unexpectedly returns `true` from this script is this:
> 
> ```
> <p id="hidden-para" hidden>This paragraph should be hidden.</p>
> ```



> The element that unexpectedly returns `true` from this script is this:
> 
> ```
> <p id="hidden-para" hidden>This paragraph should be hidden.</p>
> ```

i guess there is a style for this....

**Comment by sbabcoc** [comment]
No style... This is a standard JavaScript element attribute: https://www.w3schools.com/tags/att_hidden.asp

**Comment by rbri** [comment]
oh sorry i was blind :-D

**Comment by rbri** [comment]
@sbabcoc ok found it and it is now fixed. Its always pain to dig into this 'optimized' code.

Thanks a lot for all your hard work getting the grid stuff done.

will make a new snapshot as soon as the CI is happy with the changes.

**Comment by rbri** [comment]
@sbabcoc a new 4.4.0SNAPSHOT is out

**Comment by sbabcoc** [comment]
Good deal! I've pulled down the latest for `htmlunit3-driver` and updated to `htmlunit` 4.4.0-SNAPSHOT, and the driver unit tests are running extraordinarily slow. You're probably already aware of this, though.

**Comment by rbri** [comment]
Not really, have not seen any performance decrease. Will check

**Comment by rbri** [comment]
you can check the build times here https://jenkins.wetator.org/job/HtmlUnit%20-%20Headless/buildTimeTrend

**Comment by sbabcoc** [comment]
I built a local version of `htmlunit-driver` with **HtmlUnit** 4.4.0, and the affected test now works as expected.

**Comment by rbri** [comment]
Great.
