### ISSUE TITLE
Release 2.22

### ISSUE THREAD

**Issue by asashour** [SeleniumHQ/htmlunit-driver#15]
Please note HtmlUnit 2.22 is released, and we should also release HtmlUnitDriver 2.22.

As a side note, I guess we should have HtmlUnitDriver mentioned in [download](http://docs.seleniumhq.org/download/) page.

**Comment by asashour** [comment]
Can we release please?

**Comment by lukeis** [comment]
sorry for the long delay... guess I got distracted :)  just pushed to maven central, will be sync'd / public soon.
