### ISSUE TITLE
Incorrect positions 

### ISSUE THREAD

**Issue by marek-surek** [SeleniumHQ/htmlunit-driver#16]
I found bug, when you try to get positions of element.
E.g. Go to this page : http://reality.sme.sk/vsetky-ponuky/
Iterate By cssPath : #offerlist-list div.article-list
Look at position and location of returned webelements -> all are the same. PhantomJS returns positions correctly.

**Comment by asashour** [comment]
Can you provide your complete case with code.

**Comment by marek-surek** [comment]
Hi,
it was simply something like this :
driver.get("http://reality.sme.sk/vsetky-ponuky/")
for(WebElement we : driver.findElements("http://reality.sme.sk/vsetky-ponuky/"){
//check those values against phantomJS driver
we.getLocation();
we.getSize();
}

**Comment by asashour** [comment]
Rendering elements is outside the scope of HtmlUnit.

There are some JavaScript-level calculations for the `width` and `height`, but I guess they aren't useful in this case.

**Comment by rbri** [comment]
will close this because HtmlUnit is a headless driver that does only limited layout calculations
