### ISSUE TITLE
Massive memory usage, memory leak?

### ISSUE THREAD

**Issue by Axquaris** [SeleniumHQ/htmlunit-driver#19]
## Meta -
OS:  Windows 10
Selenium Version:  3.0.0-beta2 or 2.53.1 (problem occurs with both)
Driver:  HtmlUnitDriver
Version:  2.21

## Expected Behavior - 
Only the memory necessary to run one page should be used.
## Actual Behavior -
Memory use keeps on growing, reached 3GB in 30 minutes
## Steps to reproduce -

When using HtmlUnitDriver with JavaScript enabled, every single time a page is refreshed via
driver.navigate().refresh();
the memory usage grows and grows without bound.

The issue is most extreme when refreshing on sites with lots of javascript, however it is still visible with small html-only sites.

**Comment by barancev** [comment]
It must be a HtmlUnit issue, not the driver one.
Please report it to the HtmlUnit tracker: http://htmlunit.sourceforge.net/submittingBugs.html
