### ISSUE TITLE
Can't make seleniun run with htmlunit-driver

### ISSUE THREAD

**Issue by kalimalrazif** [SeleniumHQ/htmlunit-driver#23]
Sorry guys:

This is a totally noob question, but I can't make selenium run with htmlunit-driver. I'm using Linux and this is my command line:

```
java -cp selenium-server-standalone-3.0.0-beta3.jar:htmlunit-driver-standalone-2.21.jar org.openqa.grid.selenium.GridLauncher
```

The output is this:

```
Error: Could not find or load main class org.openqa.grid.selenium.GridLauncher
```

This is the output of java -version

```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

What I'm doing wrong?

Thanks in advance
Nomar

**Comment by kalimalrazif** [comment]
I try this too 
```
java -cp "selenium-server-standalone-3.0.0-beta3.jar:htmlunit-driver-standalone-2.21.jar" org.openqa.grid.selenium.GridLauncher
```

**Comment by lukeis** [comment]
Ah, the class name changed to GridLauncherV3

**Comment by kalimalrazif** [comment]
:-o thanks :-) you should to update the info on README.md XD
https://github.com/SeleniumHQ/htmlunit-driver/blob/master/README.md

Thanks :-)

**Comment by asashour** [comment]
I see this was done in https://github.com/SeleniumHQ/htmlunit-driver/commit/d37ccd47b035ceded45fa26ff27e454fb50d6852
