### ISSUE TITLE
Working with frames broken

### ISSUE THREAD

**Issue by surenz** [SeleniumHQ/htmlunit-driver#24]
Since release 2.21 the browser does not support frames (or at least this is the message in the body):

> You must use a browser that supports frames

Other actions as typing, clicking are working as expected until a frame element should be located.

My current setup with maven is:

```
<dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>2.53.1</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>htmlunit-driver</artifactId>
            <version>2.23</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>2.53.1</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.jetty.websocket</groupId>
            <artifactId>websocket-client</artifactId>
            <version>9.4.0.M1</version>
        </dependency>
```

The last version which works OK with frames is 2.20.
Thanks

**Comment by rbri** [comment]
Hi and sorry getting so late to this issue.
This looks like a general HtmlUnit problem to me. Please open a HtmlUnit issue if you are still facing this problem with the latest driver/htmlunit combination.
