### ISSUE TITLE
getAttribute("value") on file input doesn't work

### ISSUE THREAD

**Issue by Toilal** [SeleniumHQ/htmlunit-driver#27]
I'm upgrading from 2.21 to 2.23, but invoking `getAttribute("value")` on a HtmlFileInput element doesn't return the file path value anymore.

Any clue ? I also switched from Selenium 2.53.1 to 3.0.0-beta4.

**Comment by asashour** [comment]
Thanks for reporting.

I can produce the issue in `htmlunit-driver` 2.23, and now it passes on the `master` branch, possibly because of fixes in HtmlUnit 2.24.

Please verify and re-open if you have any issue.
