### ISSUE TITLE
Method findElementsByXPath returns an empty list in a xml page

### ISSUE THREAD

**Issue by jneira** [SeleniumHQ/htmlunit-driver#29]
Hi, i am trying to retrieve a list of elements in a xml page using xpath. The method findElementsByXPath returns an empty list if the page is not a HtmlPage:

```
 if (!(lastPage() instanceof HtmlPage)) {
      return new ArrayList<>();
    }
```

But the method findElementByXPath works fine cause it checks if it is a SgmlPage:

```
if (!(lastPage() instanceof SgmlPage)) {
      throw new IllegalStateException("Unable to locate element by xpath for " + lastPage());
    }
```

Is there a reason to this behaviour? the node retrieved in findElementByXPath is a DomNode, and i guess the nodes that would be retrieved by findElementsByXPath are too...

In firefox driver the list of nodes are retrieved.

thanks

**Comment by shs96c** [comment]
There's no reason for that behaviour. Please send a PR and we can merge it in :)

**Comment by jneira** [comment]
Sure! i am working in it: https://github.com/jneira/htmlunit-driver/tree/issue%2329

**Comment by jneira** [comment]
I think the pull request is ready, is neccesary to do something more?
