### ISSUE TITLE
HTMLUNIT fails to open XML with UTF-8 with BOM

### ISSUE THREAD

**Issue by BuckB342** [SeleniumHQ/htmlunit-driver#31]
[bomtest.zip](https://github.com/SeleniumHQ/htmlunit-driver/files/569487/bomtest.zip)

HTMLUNIT will fail to navigate and parse to an XML (or HTML Page) that has a Byte Order Mark (BOM).
An XML document in UTF-8 with BOM will yield the following error message in HTMLUnit:
"Failed Parsing XML Document.  <Filename here>: Content is not allowed in prolog.

XML with a BOM is considered legal/valid XML and should be parsed by HTMLUnit.  See attached file for example

To replicate:
driver = webdriver.Remote(remote_host_name, webdriver.DesiredCapabilities.HTMLUNITWITHJS)
driver.get(file:///C:/bomtest.xml)
Note error

**Comment by asashour** [comment]
Thanks for reporting, this is now [fixed](https://sourceforge.net/p/htmlunit/code/13302/) in HtmlUnit.
