### ISSUE TITLE
Drag and drop not working with htmlunit-driver

### ISSUE THREAD

**Issue by diogosouza** [SeleniumHQ/htmlunit-driver#33]
When simply trying to drag and drop an element in a page at htmlunit-driver:

```
new Actions(driver)).dragAndDropBy(element, 10, 10)
                     .build()
                     .perform();
```

we have the following exception:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Moving to arbitrary X,Y coordinates not supported.
```

At [class `HtmlUnitMouse`](https://github.com/SeleniumHQ/htmlunit-driver/blob/master/src/main/java/org/openqa/selenium/htmlunit/HtmlUnitMouse.java#L187) we have:

```
@Override
  public void mouseMove(Coordinates where, long xOffset, long yOffset) {
    throw new UnsupportedOperationException("Moving to arbitrary X,Y coordinates not supported.");
  }
```

Is there any way to do such this thing in htmlunit-driver?

**Comment by stiemannkj1** [comment]
@DiogoSouza,

I wonder if `mouseMove()` could be implemented like this:

```
  @Override
  public void mouseMove(Coordinates elementCoordinates, long xOffset, long yOffset) {

    DomElement element = getElementForOperation(elementCoordinates);
    moveOutIfNeeded(element);
    updateActiveElement(element);
  }
```

@DiogoSouza, can you try building the project with this code and see if that fixes your issue? Or could you provide a simple html page and steps to reproduce your issue?

**Comment by rbri** [comment]
Sorry but HtmlUnit is a headless driver - this implies there is no layouting of the pages. But without having a page layout moving the mouse to a x,y location is not supported.
