### ISSUE TITLE
findElementById never throws a NoSuchElementException

### ISSUE THREAD

**Issue by jowerner** [SeleniumHQ/htmlunit-driver#34]
When searching for an element by ID and the element could not be found on the page, HtmlUnitDriver does not throw a NoSuchElementException as expected, but returns an HtmlUnitWebElement wrapping a null DomElement.

This is because HtmlUnit's getElementById() method does not throw an exception, but returns null, if the element could not be found.

**Comment by asashour** [comment]
Thanks a lot for reporting. This change was done ten hours ago, and you detected it :)

Now it is fixed.
