### ISSUE TITLE
Issues around Implicit Wait Timeout

### ISSUE THREAD

**Issue by jowerner** [SeleniumHQ/htmlunit-driver#35]
When searching for elements, HtmlUnitDriver obeys the configured implicit wait timeout. However, there are some small issues/inconsistencies.

1. In case the implicit wait timeout is set to 0 and no element was found when doing a findElement(...), the driver performs nevertheless one round of sleeping (200 ms), but should return immediately.
2. The findElements(...) method respects the configured implicit wait timeout, but does not sleep at all between retries. This is in contrast to findElement(...) and CPU-consuming.
3. If the passed condition object is not satisfied, the method HtmlUnitDriver.implicitlyWaitFor() may or may not sleep between retries, depending on the result of the condition (null vs. Boolean.FALSE).

**Comment by asashour** [comment]
I am not sure why the implicit wait timeout is introduced. I hope other members can provide some details.

**Comment by asashour** [comment]
Point number 2 was handled in https://github.com/SeleniumHQ/htmlunit-driver/commit/24099808c9f30ea38fe12106668d4273e80d0026

**Comment by shs96c** [comment]
Implicit wait was added to allow folks not familiar with how and when their DOM changed to write more stable tests. The selenium project mostly advises people to use the explicit waits where possible.

**Comment by asashour** [comment]
Thanks for reporting.

I am closing this, since nothing much to be done.

We are moving the the 'RemoteDriver', in which the timeout is implicitly handled.
