### ISSUE TITLE
Release 2.24

### ISSUE THREAD

**Issue by asashour** [SeleniumHQ/htmlunit-driver#37]
Hi all,

Please note we are now ready to release `htmlunit-driver` 2.24. I looked into all relevant failing tests, and they are fixed either in HtmlUnit `trunk` or in the driver.

Please also update the latest release in [releases](https://github.com/SeleniumHQ/htmlunit-driver/releases).

As a side note, I guess we should have HtmlUnitDriver mentioned in Selenium [download](http://docs.seleniumhq.org/download/) page.

Thanks,

**Comment by asashour** [comment]
@lukeis may I ask to get permission to release HtmlUnitDriver in maven repository.

Also, HtmlUnit test suite depends on the driver, and this cross-dependency is difficult to handle, without failing tests, or waiting for the other project to release.

Having the ability to deploy snapshots on both projects makes it easier to maintain.

**Comment by shs96c** [comment]
@asashour, I've added htmlunitdriver to the download page. Please feel free to send a PR to the [site's GH project](https://github.com/SeleniumHQ/www.seleniumhq.org) when you want to change any details such as the released version number.

**Comment by asashour** [comment]
Thanks Simon, I didn't make a PR because I couldn't decide where it should exist in the page.

**Comment by asashour** [comment]
2.24 was released, thanks.
