### ISSUE TITLE
org.seleniumhq.selenium:htmlunit-driver:2.23.1 vs. org.seleniumhq.selenium:selenium-htmlunit-driver:2.52.0

### ISSUE THREAD

**Issue by kriegaex** [SeleniumHQ/htmlunit-driver#38]
Sorry if this is the wrong place to ask, but I don't know ehere else to. In different POMs I see dependencies like
- org.seleniumhq.selenium:**htmlunit-driver:2.23.1** and
- org.seleniumhq.selenium:**selenium-htmlunit-driver:2.52.0**.

Different artifact names and different versions leave me in doubt which one is the more "official" and the better maintained version. Sorry for being confused. Furthermore, most official Selenium Maven artifacts have been updated synchronously to 3.0.1, so both 2.52.0 and 2.23.1 seem a bit odd.

**Comment by asashour** [comment]
Hi, please use:

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>htmlunit-driver</artifactId>
            <version>2.23.2</version>
        </dependency>

The names were changed and the version now matches HtmlUnit dependency.
