### ISSUE TITLE
Where is htmlunit-driver-standalone-2.x.jar

### ISSUE THREAD

**Issue by phystem** [SeleniumHQ/htmlunit-driver#39]
After **htmlunit-driver-standalone-2.21.jar** there is no further releases for standalone jar. when it is will released. If so add it to the Release Page

**Comment by asashour** [comment]
Thanks for hinting.

https://github.com/SeleniumHQ/htmlunit-driver/releases/tag/2.24 was released, hope you don't mind the name change.
