### ISSUE TITLE
Html unit driver is throwing an error if we launch the browser 

### ISSUE THREAD

**Issue by prasanna532** [SeleniumHQ/htmlunit-driver#43]
Exception in thread "main" org.openqa.selenium.WebDriverException: java.lang.IllegalArgumentException: Cannot locate declared field class org.apache.http.impl.client.HttpClientBuilder.dnsResolver

**Comment by prasanna532** [comment]
Selenium version 2.53.1
trying with html unitdriver 2.25 with all dependencies jar.

**Comment by asashour** [comment]
Please change the artifactId:

You don't need to include `Selenium`, it is implicitly referenced.

The latest version is:

```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>htmlunit-driver</artifactId>
    <version>2.25</version>
</dependency>
```
