### ISSUE TITLE
Not clicking the hiiden button where css applied 'display:none'

### ISSUE THREAD

**Issue by ramneesh** [SeleniumHQ/htmlunit-driver#50]
This issue is similar to "https://github.com/SeleniumHQ/htmlunit-driver/issues/46".

When button component is like :

<button  type="submit" class="hideOnLoad"  id="viewTarget" name="viewTarget" value="viewTarget">

CSS : .hideOnLoad{
           display:none
         }

Now firefox webdriver could able to click above button with jquery 
     $('#viewTarget').click();

Where as in HtmlUnitDriver version 2.26 and 2.27 its not able to click the button.

Please provide the solution for this. My email id is : ramneesh.choudhary@mindtree.com

Regards
Ramneesh

**Comment by ramneesh** [comment]
above comment not displaying button syntax so posted again :

button  type="submit" class="hideOnLoad"  id="viewTarget" name="viewTarget" value="viewTarget"

**Comment by rbri** [comment]
This was fixed with the last HtmlUnit release (2.29). There is also a matching selenium driver available. Sorry for the late feedback.
