### ISSUE TITLE
import org.openqa.selenium.htmlunit.HtmlUnitDriver; can not be resolved

### ISSUE THREAD

**Issue by beshoo** [SeleniumHQ/htmlunit-driver#54]
Dear all , after adding the "HtmlUnitDriver" to pom.xml and installing it , 
import org.openqa.selenium.htmlunit.HtmlUnitDriver; can not be resolved!

http://i.imgur.com/kUyePPn.png

Please advice

**Comment by barancev** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)
