### ISSUE TITLE
[SOLVED] DOM/JavaScript memory leak

### ISSUE THREAD

**Issue by rickardoberg** [SeleniumHQ/htmlunit-driver#55]
As per issue #49 there is a severe memory leak, and while it applies to all uses of Htmlunitdriver it becomes really obvious when JavaScript is used, because of how much memory is used.

Long story short, I used VisualVM to track down what was holding the scriptable objects, and it turned out to be HtmlUnitDriver.elementsMap. Specifically the memory leak happens [here](https://github.com/SeleniumHQ/htmlunit-driver/commit/bc92f47db68627d2081f13212629c8e9ae918cde#diff-ab0992d06ffc787375fc606b2b2f4058R1091
).

The map is populated, but not cleared on browsing to new page. Make a HtmlUnitDriver subclass with the following override fixes the issue:
`    

    @Override
    protected WebClient modifyWebClient( WebClient client )
    {
        try
        {
            Field field = getClass().getSuperclass().getDeclaredField( "elementsMap" );
            field.setAccessible( true );

            client.addWebWindowListener( new WebWindowListener()
            {
                @Override
                public void webWindowOpened( WebWindowEvent webWindowEvent )
                {
                }

                @Override
                public void webWindowContentChanged( WebWindowEvent event )
                {

                    try
                    {
                        Map map = (Map) field.get( ExtendedHtmlUnitDriver.this );
                        map.clear();
                    }
                    catch ( IllegalAccessException e )
                    {
                        e.printStackTrace();
                    }
                }

                @Override
                public void webWindowClosed( WebWindowEvent event )
                {
                }
            } );

        }
        catch ( NoSuchFieldException e )
        {
            e.printStackTrace();
        }

        return client;
    }
`

Workaround:
Until the issue is fixed, users can create custom subclasses with the above fix to avoid the memory leak.

**Comment by rbri** [comment]
Think i have done a fix for this. Please try the latest snapshot (2.29-SNAPSHOT).

Please inform about the result.

**Comment by rbri** [comment]
Will close this.
