### ISSUE TITLE
Driver always throwing UnhandledAlertException even when alert is handled

### ISSUE THREAD

**Issue by lostiniceland** [SeleniumHQ/htmlunit-driver#57]
The method ensureAlertUnlocked is [always throwing an UnhandledAlertException](https://github.com/SeleniumHQ/htmlunit-driver/blob/2.27/src/main/java/org/openqa/selenium/htmlunit/HtmlUnitDriver.java#L748) even though the alert has been accepted/dismissed.

Since the ignore-case is doing nothing, I assume that the Exception should be part of this case and the curly is just at the wrong place.

This hit us in one of our legacy-applications which we are now safeguarding with tests (we set "unexpectedAlertBehaviour" to "accept"). The tests passed in all drivers except HtmlUnit. I've tested a local build where the exception is only thrown in the IGNORE-case and now everthing is fine.

**Comment by rbri** [comment]
Have done some fixes; now all the related tests are passing. Thanks for this report.
Please check and report if you think there is still a problem.
