### ISSUE TITLE
NullPointerException when calling getTitle() and alert is present

### ISSUE THREAD

**Issue by carlosaml** [SeleniumHQ/htmlunit-driver#61]
Operations that internally call `ensureAlertUnlocked()` method (e.g. `getTitle()`) will get a `NullPointerException` when there's an alert present on the page **and** the HtmlUnitDriver constructor used was **not** the one that takes a `Capabilities` object in. It seems like this is the only constructor that sets a default value for the `unexpectedAlertBehaviour` field.

Below are a few test cases (based on the existing `AlertsTest` class) that reproduce the issue. The first two fail and the last one passes, since it creates the driver by using the constructor that takes the `Capabilities` object.

```java
  // FAILS
  @Test(expected = UnhandledAlertException.class)
  public void booleanConstructor() {
    HtmlUnitDriver driver = new HtmlUnitDriver(true);

    driver.get(alertPage("cheese"));
    driver.findElement(By.id("alert")).click();

    assertEquals("Testing Alerts", driver.getTitle());
  }

  // FAILS
  @Test(expected = UnhandledAlertException.class)
  public void browserVersionAndBooleanConstructor() {
    HtmlUnitDriver driver = new HtmlUnitDriver(BrowserVersion.BEST_SUPPORTED, true);

    driver.get(alertPage("cheese"));
    driver.findElement(By.id("alert")).click();

    assertEquals("Testing Alerts", driver.getTitle());
  }

  // PASSES
  @Test(expected = UnhandledAlertException.class)
  public void capabilitiesConstructor() {
    HtmlUnitDriver driver = new HtmlUnitDriver(new DesiredCapabilities(BrowserType.HTMLUNIT, null, Platform.ANY));

    driver.get(alertPage("cheese"));
    driver.findElement(By.id("alert")).click();

    assertEquals("Testing Alerts", driver.getTitle());
  }
```

**Comment by rbri** [comment]
Fixed with the latest snapshot build. Many thanks for the test cases and the analysis.
