### ISSUE TITLE
java.lang.NoClassDefFoundError: org/openqa/selenium/ElementNotInteractableException

### ISSUE THREAD

**Issue by redochka** [SeleniumHQ/htmlunit-driver#64]
I am getting this error as soon as i do: `driver = new HtmlUnitDriver();`

The problem happens on armV7l 

<pre>
2017-11-16 15:44:06.213 ERROR 31324 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch fa
iled; nested exception is java.lang.NoClassDefFoundError: org/openqa/selenium/ElementNotInteractableException] with root cause

java.lang.ClassNotFoundException: org.openqa.selenium.ElementNotInteractableException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_151]
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.resetKeyboardAndMouseState(HtmlUnitDriver.java:698) ~[htmlunit-driver-2.28.jar:na]
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:693) ~[htmlunit-driver-2.28.jar:na]
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.get(HtmlUnitDriver.java:646) ~[htmlunit-driver-2.28.jar:na]
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:256) ~[htmlunit-driver-2.28.jar:na]
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:208) ~[htmlunit-driver-2.28.jar:na]
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:198) ~[htmlunit-driver-2.28.jar:na]
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.<init>(HtmlUnitDriver.java:188) ~[htmlunit-driver-2.28.jar:na]

</pre>

<pre>
        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;selenium-java&lt;/artifactId&gt;
            &lt;version&gt;3.7.1&lt;/version&gt;
        &lt;/dependency&gt;
        &lt;dependency&gt;
            &lt;groupId&gt;net.sourceforge.htmlunit&lt;/groupId&gt;
            &lt;artifactId&gt;htmlunit&lt;/artifactId&gt;
            &lt;version&gt;2.28&lt;/version&gt;
        &lt;/dependency&gt;
        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;htmlunit-driver&lt;/artifactId&gt;
            &lt;version&gt;2.28&lt;/version&gt;
        &lt;/dependency&gt;
</pre>

**Comment by rbri** [comment]
Please try 2.29-SNAPSHOT as the snapshot is compiled against 3.7.1.

And report your results.

**Comment by redochka** [comment]
same problem.
tested on both arm and x86 servers
do i have to set Xvfb because it's headless?

**Comment by redochka** [comment]
also, in idea i have : canno't resolve symbol htmlunit for : `import org.openqa.selenium.htmlunit.HtmlUnitDriver;`

**Comment by rbri** [comment]
Looks like a classpath problem. Your are sure the selenium stuff is in your clsspath?

**Comment by redochka** [comment]
maven dependencies looks ok. See screenshot:
![htmlunit-deps](https://user-images.githubusercontent.com/263297/32939843-2752b61c-cb81-11e7-910a-6679ca56f366.png)

**Comment by redochka** [comment]
ah the screenshot shows that html-driver is missing. i replaced the `2.29-SNAPSHOT` by `2.28` in the following:

<pre>
        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;htmlunit-driver&lt;/artifactId&gt;
            &lt;version&gt;2.28&lt;/version&gt;
        &lt;/dependency&gt;
</pre>

And now the dependency is added and everything is working as expected.

Thanks for the help @rbri

**Comment by rbri** [comment]
Ok great. You are right, the current html-unit driver snapshot unses the htmlunit release. I can understand that this is confusing. Sorry.
I think there is no need for defining the HtmlUnit dependency in your pom because this is already referenced from the html-unit driver package.

**Comment by redochka** [comment]
when i comment the htmlUnit dependency, i see these 3 dependencies added:
<pre>
- htmlunit: 2.21
- htmlunit-core-js: 2.17
- neko-htmlunit: 2.21
</pre>
Quite old..

Whereas with the dependency defined, i have: 
<pre>
- htmlunit: 2.29-SNAPSHOT
- htmlunit-core-js: 2.28
- neko-htmlunit: 2.28

</pre>

**Comment by redochka** [comment]
For archiving purpose, the problem is that old selenium dependencies were in the classpath, the fix is to define all selenium dependecies / HtmlUnit to avoid old transitive ones.

Relevant part of the pom which is working now is:

<pre>
        &lt;dependency&gt;
            &lt;groupId&gt;net.sourceforge.htmlunit&lt;/groupId&gt;
            &lt;artifactId&gt;htmlunit&lt;/artifactId&gt;
            &lt;version&gt;2.28&lt;/version&gt;
        &lt;/dependency&gt;

        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;htmlunit-driver&lt;/artifactId&gt;
            &lt;version&gt;2.28&lt;/version&gt;
        &lt;/dependency&gt;


        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;selenium-api&lt;/artifactId&gt;
            &lt;version&gt;3.7.1&lt;/version&gt;
        &lt;/dependency&gt;

        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;selenium-support&lt;/artifactId&gt;
            &lt;version&gt;3.7.1&lt;/version&gt;
        &lt;/dependency&gt;

        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;selenium-remote-driver&lt;/artifactId&gt;
            &lt;version&gt;3.7.1&lt;/version&gt;
        &lt;/dependency&gt;


        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;selenium-java&lt;/artifactId&gt;
            &lt;version&gt;3.7.1&lt;/version&gt;
        &lt;/dependency&gt;


        &lt;dependency&gt;
            &lt;groupId&gt;org.seleniumhq.selenium&lt;/groupId&gt;
            &lt;artifactId&gt;selenium-chrome-driver&lt;/artifactId&gt;
            &lt;version&gt;3.7.1&lt;/version&gt;
        &lt;/dependency&gt;
</pre>

**Comment by rbri** [comment]
> when i comment the htmlUnit dependency, i see these 3 dependencies added:
> - htmlunit: 2.21
> - htmlunit-core-js: 2.17
> - neko-htmlunit: 2.21> 

Strange; the pom from htmlunit-driver 2.29-SNAPSHOT points to
 - htmlunit 2.28
and htmlunit 2.28 refers
 - htmlunit-core-js 2.28
 - neko-htmlunit 2.28
 - ....

Can you pleas try to figure out if some other part of your pom point to this outdated htmlunit stuff.

**Comment by redochka** [comment]
Here is the relevant part of : `mvn dependency:tree -Dverbose`

<pre>
[INFO] +- org.seleniumhq.selenium:htmlunit-driver:jar:2.28:compile
[INFO] |  +- (org.seleniumhq.selenium:selenium-api:jar:2.53.1:compile - version managed from 3.7.0; omitted for conflict with 3.7.1)
[INFO] |  +- (org.seleniumhq.selenium:selenium-support:jar:2.53.1:compile - version managed from 3.7.0; omitted for conflict with 3.7.1)
[INFO] |  \- net.sourceforge.htmlunit:htmlunit:jar:2.21:compile (version managed from 2.28)
[INFO] |     +- xalan:xalan:jar:2.7.2:compile
[INFO] |     |  \- xalan:serializer:jar:2.7.2:compile
[INFO] |     +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |     +- (org.apache.httpcomponents:httpclient:jar:4.5.3:compile - version managed from 4.5.1; omitted for duplicate)
[INFO] |     +- org.apache.httpcomponents:httpmime:jar:4.5.3:compile (version managed from 4.5.2)
[INFO] |     |  \- (org.apache.httpcomponents:httpclient:jar:4.5.3:compile - version managed from 4.5.2; omitted for duplicate)
[INFO] |     +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.17:compile
[INFO] |     +- net.sourceforge.htmlunit:neko-htmlunit:jar:2.21:compile
</pre>

maybe you should update update htmlunit-driver pom.xml to use latest selenium driver version:

<pre>
from:
    &lt;selenium.version&gt;3.7.0&lt;/selenium.version&gt;
to:
    &lt;selenium.version&gt;3.7.1&lt;/selenium.version&gt;

</pre>

**Comment by rbri** [comment]
> maybe you should update update htmlunit-driver pom.xml to use latest selenium driver version:

That is already done and the reason why i have suggested to use htmlunit-driver:2.29-SNAPSHOT (in my first comment for this).
Can you please verify that the snapshot produces the correct dependencies for you.

**Comment by redochka** [comment]
<pre>
[INFO] +- org.seleniumhq.selenium:htmlunit-driver:jar:2.29-SNAPSHOT:compile
[INFO] |  +- (org.seleniumhq.selenium:selenium-api:jar:2.53.1:compile - version managed from 3.7.1; omitted for conflict with 3.7.1)
[INFO] |  +- (org.seleniumhq.selenium:selenium-support:jar:2.53.1:compile - version managed from 3.7.1; omitted for conflict with 3.7.1)
[INFO] |  \- net.sourceforge.htmlunit:htmlunit:jar:2.21:compile (version managed from 2.28)
</pre>


I don't understand the: `version managed from 3.7.1; omitted for conflict with 3.7.1) `

**Comment by rbri** [comment]
Can you please send me you whole pom to my private mail.

**Comment by redochka** [comment]
how to find your private email?

**Comment by rbri** [comment]
If you need support you have to solve that :-)
Have a look at the developer list on the HtmlUnit web site - Project Information - Team

**Comment by redochka** [comment]
Great 👍 I found it. check your emails

2017-11-18 21:44 GMT+01:00 RBRi <notifications@github.com>:

**Comment by rbri** [comment]
Ok, took a bit longer to understand....

Your pom includes the spring boot as parent. And sadly this points to the outdated HtmlUnit 2.21.
