### ISSUE TITLE
2.28.3 requires 2.29-SNAPSHOT

### ISSUE THREAD

**Issue by acdcjunior** [SeleniumHQ/htmlunit-driver#67]
`2.28.3` is depending on htmlunit `2.29-SNAPSHOT` which doesn't exist on maven central.

Deployed pom: http://central.maven.org/maven2/org/seleniumhq/selenium/htmlunit-driver/2.28.3/htmlunit-driver-2.28.3.pom

```
<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <selenium.version>3.8.1</selenium.version>
  <htmlunit.version>2.29-SNAPSHOT</htmlunit.version>
</properties>
```

**Comment by rbri** [comment]
Ups ma fault. the new version is on the way
