### ISSUE TITLE
The released package '-jar-with-dependencies' does not include the driver itself

### ISSUE THREAD

**Issue by lucasvc** [SeleniumHQ/htmlunit-driver#68]
I'm migrating from Selenium 3.4.0 to 3.8.1, and I've realized that `HtmlUnitDriver` **again** is not bundled with Selenium.
Ok, a good modularization move.
I was then downloading the release package [`htmlunit-driver-2.28.4-jar-with-dependencies.jar`](htmlunit-driver-2.28.4-jar-with-dependencies.jar), which I suposed would be the driver itself and all the dependencies needed (as for now, I can't use Maven in my environment).
But inside the jar, there is no package `org.openqa.selenium.htmlunit`.
It is supposed to download that _fatjar_ **and** the maven artifact by hand?

**Comment by rbri** [comment]
You are right; my fault. A new release is available. Thanks for your report.
