### ISSUE TITLE
Selenium test suite

### ISSUE THREAD

**Issue by asashour** [SeleniumHQ/htmlunit-driver#7]
Hi all,

The tests in `htmlunit-driver` don't have all the tests from the Selenium project.

I guess should be references/copied, so failing tests could be fixed.

An example of sharing test code in maven is [here](http://stackoverflow.com/questions/174560/sharing-test-code-in-maven).

**Comment by lukeis** [comment]
problem is that the main selenium repo doesn't use maven at all for the tests, so trying to use maven to share the test code isn't going to be plausible.

Also I've given you commit rights to this repo... have at whatever you'd like in here :)

**Comment by asashour** [comment]
Thanks so much.

I will add the test suite from the main repository.

In the meantime, can we release htmlunit-driver 2.21, since htmlunit 2.21 is already released?

**Comment by lukeis** [comment]
i'll try to find some time to push it to make a release

**Comment by lukeis** [comment]
@asashour just pushed 2.21 release

**Comment by asashour** [comment]
Thanks a lot

**Comment by asashour** [comment]
Another question. I plan to move the test cases from main repo to here.

1. Keeping the test history seems to rewrite history, and this could be dangerous, please see [here](http://stackoverflow.com/questions/1365541/how-to-move-files-from-one-git-repo-to-another-not-a-clone-preserving-history)
2. The other way to to simply copy & paste without keeping the test history.

What is suggested?

**Comment by lukeis** [comment]
I usually tend to like to keep history if possible. Try it first, if it looks like it will corrupt the repo, then just copy
