### ISSUE TITLE
HtmlUnitDriver doesn't support console logs

### ISSUE THREAD

**Issue by yair-jarvis** [SeleniumHQ/htmlunit-driver#70]
Hi
I was trying to read browser level console logs for a test that I'm running. 
When I type driver.manage().logs() I get an "UnsupportedOperationException("Driver does not support this operation.")"

I looked at the HtmlUnitDriver source code and saw that it overrides the WebDriver logs method.
Is there another way to read console logs using HtmlUnitDriver? 
Thanks,
Yair

**Comment by rbri** [comment]
Sorry not for the moment. Maybe i can add support for that.

**Comment by rbri** [comment]
have added the support in version 2.35.0. Please keep in mind that the API is marked as beta from the selenium folks.
