### ISSUE TITLE
为什么执行quit()，程序仍在运行，不结束呢？

### ISSUE THREAD

**Issue by erbozhao** [SeleniumHQ/htmlunit-driver#76]
HtmlUnitDriver driver = new HtmlUnitDriver();
 driver.setJavascriptEnabled(true);
 driver.get("http://www.baidu.com/");
 driver.quit();

**Comment by rbri** [comment]
Sorry for the late response, but i was confused by the Chinese title....

Not sure what you expect. The driver loads the page ans starts the javascript processing in a separate thread. And there is nothing more to do for the main thread; quit is called.
Why do you expect that this waits for something and for what this should wait.

This is more or less the same code as a user starts his browser, types in the url and then closes the browser just in the moment the initial processing is done and javascripts takes over.

**Comment by rbri** [comment]
sorry - but without any further feedback from the reporter i can't do anything.
Will close this.
Please open a new one if you still have problems.
