### ISSUE TITLE
getText() doesn't seem to respect CSS property "white-space"

### ISSUE THREAD

**Issue by quiram** [SeleniumHQ/htmlunit-driver#80]
When a web element has the CSS property `white-space: pre-wrap`, browsers are supposed to render text without consolidating white space. Since, according to the spec, `getText()` is supposed to return text exactly as rendered, calling it for an element with the aforementioned style should return all the existing white space (without consolidation). This is not the case for htmlunit-driver. This way, for the text "Hello&nbsp;&nbsp;&nbsp;&nbsp;World":

- Expected result: "Hello&nbsp;&nbsp;&nbsp;&nbsp;World"
- Actual result: "Hello World"

I have tried with Chrome, IE, and Firefox Drivers and in all three cases I get the expected result, reason for which I believe it to be specific to htmlunit-driver.

I know this issue seems similar to [Selenium getText is normalizing white space](https://github.com/SeleniumHQ/selenium/issues/2608), but I believe it to be different.

*Further details*:
Selenium version: 3.141.59
HtmlUnitDriver version: 2.35.0
Java version: 1.8.0_192-b12

**Comment by quiram** [comment]
On further inspection, I believe the issue might be in `HtmlSerializer`, most precisely in line 51:

```
if (!(element instanceof HtmlElement)) {
  text = text.replaceAll("\\p{javaWhitespace}+", " ").trim(); // line 51
}
```

I could try to do a PR if that helps?

**Comment by rbri** [comment]
Am 30. August 2019 16:18:00 MESZ schrieb Abraham Marin-Perez <notifications@github.com>:
>On further inspection, I believe the issue might be in
>`HtmlSerializer`, most precisely in line 51:
>
>```
>if (!(element instanceof HtmlElement)) {
> text = text.replaceAll("\\p{javaWhitespace}+", " ").trim(); // line 51
>}
>```
>
>I could try to do a PR if that helps?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SeleniumHQ/htmlunit-driver/issues/80#issuecomment-526619115

PRs are always welcome, and even more welcome if they have unit tests.

**Comment by quiram** [comment]
Hi @rbri. I actually deleted that comment after I started trying to do the PR and realised the problem isn't where I initialised thought 😛. I will still try, but now I'm less confident I'll be able to hit the mark.

**Comment by rbri** [comment]
Am 30. August 2019 18:49:21 MESZ schrieb Abraham Marin-Perez <notifications@github.com>:
>Hi @rbri. I actually deleted that comment after I started trying to do
>the PR and realised the problem isn't where I initialised thought 😛. I
>will still try, but now I'm less confident I'll be able to hit the
>mark.>
>>
>>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/SeleniumHQ/htmlunit-driver/issues/80#issuecomment-526671463

No problem but I'm currently not at home, maybe I can work on this in one week.

**Comment by quiram** [comment]
It’s ok. We have disabled this particular test for htmlunit-driver for now, but we can still run with other browsers, so we’re fine for now. Thanks!

**Comment by rbri** [comment]
A major change for this is on the way... will make a new snapshot build available soon.

**Comment by rbri** [comment]
This is now available. Please check the latest release and report any remaining problems.
