### ISSUE TITLE
Missing customizability 'ajaxController'

### ISSUE THREAD

**Issue by 616slayer616** [SeleniumHQ/htmlunit-driver#81]
Setting the ajaxController of the HtmlUnit WebClient can be very helpful when testing interactions with ajax.

See [http://htmlunit.sourceforge.net/faq.html#AJAXDoesNotWork](http://htmlunit.sourceforge.net/faq.html#AJAXDoesNotWork)

Since the WebClient is completely inaccessible from outside the HtmlUnitDriver calling `setAjaxController` is not possible.

There should either be a way to set the ajax controller or to access the web client (this might be useful for other interactions as well).

Calling
`webClient.setAjaxController(new NicelyResynchronizingAjaxController());`
makes my tests work perfectly.

**Comment by rbri** [comment]
Have added a sample for customization to https://github.com/SeleniumHQ/htmlunit-driver/blob/master/README.md one week ago.

**Comment by 616slayer616** [comment]
Thanks.
I didn't even think of that.
