### ISSUE TITLE
getText() doesn't get text of child elements

### ISSUE THREAD

**Issue by quiram** [SeleniumHQ/htmlunit-driver#82]
Consider the following HTML structure (within a properly constructed page)

```html
<label>The text to be <span>tested</span></label>
```

When running the following in Selenium WebDriver, I would expect to get the whole text:
```java
webDriver.findElement(By.tagName("label")).getText();
// Expected: "The text to be tested"
// Actual: "The text to be"
```
Instead, the text that is obtained excludes the text of the inner element.

I can confirm this works as expected with other drivers like Chrome or Firefox.

**Comment by rbri** [comment]
Many thanks for your report.

Have rewritten the getText support of the HtmlUnit driver for the upcoming version 2.37.0. This is now fixed.

Will make a new snapshot build available soon. Please check on twitter (https://twitter.com/HtmlUnit) for info about new snapshots/releases.
