### ISSUE TITLE
Selenium 4 support

### ISSUE THREAD

**Issue by slawekradzyminski** [SeleniumHQ/htmlunit-driver#90]
Hi htmlunit-driver developers :) 

What are your plans regarding Selenium 4? Do you plan to release version supporting alpha/beta or do you wait for proper release? 

I'm asking because we use it heavily in [FluentLenium](https://github.com/FluentLenium/FluentLenium/pull/1084) and our whole integration suite fails right now with Selenium 4.

Thanks in advance for your response

**Comment by sachinhr10** [comment]
Adding on to it, we are testing the selenium 4 alpha and beta version and we have a dependency conflict to the selenium-support from html-unit-driver. If you could provide an alpha or beta version of html-unit-driver for testing, it'd be helpful. 

Thank you

**Comment by qqilihq** [comment]
Any news or statement from the maintainers?

**Comment by sbabcoc** [comment]
Try here: https://github.com/HtmlUnit/htmlunit-driver4

**Comment by qqilihq** [comment]
> Try here: https://github.com/HtmlUnit/htmlunit-driver4

This is only generated stub code. Nothing which works.

Considering that this issue is now 1+ year old, I'd assume that there's no interest of the maintainers to provide Selenium 4 support.

**Comment by rbri** [comment]
> Considering that this issue is now 1+ year old, I'd assume that there's no interest of the maintainers to provide Selenium 4 support.

That is not correct - i like to do it (and that is the reason why i opened the new repo for that). But at the moment i'm more or less the only person working on HtmlUnit, the CssParser, doing the required Rhino things and the HtmlUnit driver. You can have a look at https://www.openhub.net/accounts/RBRi for more details. And please keep in mind i'm doing all this in my spare time having a real >40 h job and a family.

So pull requests are welcome and sponsoring also....

**Comment by qqilihq** [comment]
Thank you for the feedback, @rbri and apologies if this sounded presumptuous. I realize the effort required to maintain such a project -- an official, prominent statement “looking support” would probably make the situation more clear and help to acquire potential supporters. I will have a look at the link, and see if there’s something where I could support, despite being in a similar situation like you.

**Comment by mabartos** [comment]
I've started to working on that. Moreover, I need to fix some issues and tests as well. It also needs to be refactored. You can check the progress here [Selenium4 upgrade](https://github.com/mabartos/htmlunit-driver/tree/selenium4).
