### ISSUE TITLE
Why is getWebClient a protected method?

### ISSUE THREAD

**Issue by jschlade** [SeleniumHQ/htmlunit-driver#95]
Hi,

Again thanks to all the developers contributing to this project.

I would like to petition that you make getWebClient public so we don't have to extend HtmlUnitDriver to get access to it. Having to write stub code to do this is not good.

There are many use cases where there's a need for this as this is project is a driver for HtmlUnit and WebClient is an object that should be more accessible and not protected in this case.

Thank you

**Comment by rbri** [comment]
Sorry for being that late on this. The method is now public in 2.64 and 3.64
