### ISSUE TITLE
The proxy settings cannot be used normally

### ISSUE THREAD

**Issue by Fcukcpp** [SeleniumHQ/htmlunit-driver#98]
String proxyUri = Jsoup.connect(api).get().text();
        Proxy proxy = new Proxy();
        proxy.setHttpProxy(proxyUri);
        DesiredCapabilities capabilities = DesiredCapabilities.htmlUnit();
        capabilities.setCapability(CapabilityType.PROXY, proxy);
        WebDriver driver = new HtmlUnitDriver(capabilities)
        {
            @Override
            protected WebClient modifyWebClient(WebClient client)
            {

                return client;
            }
        };
        driver.get("http://www.baidu.com");
        System.out.println(driver.getPageSource());

**Comment by rbri** [comment]
From what i can see here in the source the proxy is set. But this is done AFTER the modifyWebClient() was called.
Think this is not the expected behavior, the modifyWebClient() should always be called after the internal webClient setup is complete.

**Comment by rbri** [comment]
Made a bunch of fixes for the setup, please try the latest snapshot build 2.51.0-SNAPSHOT

**Comment by Fcukcpp** [comment]
> From what i can see here in the source the proxy is set. But this is done AFTER the modifyWebClient() was called.
> Think this is not the expected behavior, the modifyWebClient() should always be called after the internal webClient setup is complete.
So how do you write the code

**Comment by rbri** [comment]
Sorry but i did not get the point of your last comment

Changes:
The modifyWebClient() is now always the last call in the call chain of any of the various HtmlUnitDriver constructors.
This means, the whole internal webClient setup is done when your modifyWebClient() method gets called.

Regarding to your case - you will see all the features enabled/disabled you have defined in the capabilities.

Does this make it more clear?

**Comment by Fcukcpp** [comment]
thank you 谢谢

**Comment by rbri** [comment]
Have you tested it?

**Comment by rbri** [comment]
BTW have pushed the code change in case you like to have a look.

**Comment by Fcukcpp** [comment]
Is there a demo code

**Comment by rbri** [comment]
you can have a look at the added unit tests

**Comment by rbri** [comment]
but you are right, i can add some more samples to the readme - will do that later today

**Comment by Fcukcpp** [comment]
okay
