### ISSUE TITLE
Didn't find class "java.awt.geom.AffineTransform"

### ISSUE THREAD

**Issue by MichelNassour** [SeleniumHQ/htmlunit-driver#99]
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/geom/AffineTransform;

Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.geom.AffineTransform" on path: DexPathList[[zip file ......

**Comment by rbri** [comment]
can you please add some more details
* htmlunit version
* htmlunit driver version
* selenium version
* jdk version
* platform

**Comment by rbri** [comment]
You are on android?
Can you please post the complete stack trace?

**Comment by MichelNassour** [comment]
htmlunit **2.51.0**
htmlunit-driver  **2.51.0**
platform: android 8.0.0

**Comment by rbri** [comment]
Looks like a problem on android - the java.awt classes are not available there.

Without a stack trace i can only guess - maybe the SVGMatrix is the problem. Have rewritten the class to no longer require the classes from the java.awt namespace.

Please check on twitter - will inform there about the next snapshot build. Please test then with the new snapshot and inform about the results.

**Comment by MichelNassour** [comment]
Many thanks for your great job!

**Comment by rbri** [comment]
You are welcome and thanks for this report. It was a lot of fun to hack this.

**Comment by sbabcoc** [comment]
Oh, yeah... I have to run in Xfce4 on Arch Linux on my Android phone to get image capture to work.

**Comment by rbri** [comment]
@sbabcoc i fear you are a bit too optimistic here - i have removed the dependency only from SVGMatrix. If you are using the Canvas you are still need a lot awt stuff.

**Comment by sbabcoc** [comment]
I declare many dependencies on my class path, but not awt: https://github.com/sbabcoc/Selenium-Foundation/blob/8915291e1666434b9dc2d5de8095ad8a33c458ad/src/main/java-s3/com/nordstrom/automation/selenium/plugins/HtmlUnitPlugin.java#L29

I guess that must mean I'm not using the Canvas.
